services:
  brainsight:
    image: ${BRAINSIGHT_IMAGE}
    expose:
      - "8501"
    labels:
      - traefik.enable=true
      - traefik.http.routers.brainsight.rule=Host(`${BRAINSIGHT_HOST}`)
      - traefik.http.routers.brainsight.entrypoints=websecure
      - traefik.http.routers.brainsight.tls=true
      - traefik.http.routers.brainsight.tls.certresolver=letsencrypt
      - traefik.http.services.brainsight.loadbalancer.server.port=8501
    restart: unless-stopped
    mem_limit: 900m
    cpus: 1.00

  getaround:
    image: ${GETAROUND_IMAGE}
    expose:
      - "8501"
    labels:
      - traefik.enable=true
      - traefik.http.routers.getaround.rule=Host(`${GETAROUND_HOST}`)
      - traefik.http.routers.getaround.entrypoints=websecure
      - traefik.http.routers.getaround.tls=true
      - traefik.http.routers.getaround.tls.certresolver=letsencrypt
      - traefik.http.services.getaround.loadbalancer.server.port=8501
    restart: unless-stopped
    mem_limit: 900m
    cpus: 1.00

  fraudstream:
    image: ${FRAUDSTREAM_IMAGE}
    expose:
      - "8501"
    labels:
      - traefik.enable=true
      - traefik.http.routers.fraudstream.rule=Host(`${FRAUDSTREAM_HOST}`)
      - traefik.http.routers.fraudstream.entrypoints=websecure
      - traefik.http.routers.fraudstream.tls=true
      - traefik.http.routers.fraudstream.tls.certresolver=letsencrypt
      - traefik.http.services.fraudstream.loadbalancer.server.port=8501
    restart: unless-stopped
    mem_limit: 1200m
    cpus: 1.20
