services:
  brainsight:
    profiles: ["heavy"]
    mem_limit: 1400m
    cpus: 1.50

  getaround:
    profiles: ["heavy"]
    mem_limit: 1400m
    cpus: 1.50

  fraudstream:
    profiles: ["heavy"]
    mem_limit: 2000m
    cpus: 2.00
